[build]
  command = "npm run build"
  publish = "netlify/public"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

# Redirect Rules
[[redirects]]
  from = "/*"
  to = "/mlm-platform/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/mlm-platform"
  status = 301

# Header Rules
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://apis.example.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://images.unsplash.com; font-src 'self'; connect-src 'self' https://api.example.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add these Next.js specific headers
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  NEXT_PUBLIC_NETLIFY = "true"
  NETLIFY_MLM_FEATURES = "compression,auto-placement,commission-calc"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[plugins]]
  package = "netlify-plugin-cypress"
  
[[plugins]]
  package = "netlify-plugin-lighthouse"